version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run: sudo apt install -y dpkg-dev
      - run: ./build-source.sh
      - run: ./build-package.sh full --no-sign
